/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Server;

/**
 *
 * @author lucas
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    private boolean botonPulsado = false;
    private Colonia c;
    
    public InterfazPrincipal() {
        initComponents();
        c = new Colonia(jExterior, jColonia, jInstruccion,
                jDescanso, jAlmacen, jContAlmacen, 
                jLlevando, jComedor, jContComedor);
        Generador generador = new Generador(c);
        generador.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jExterior = new javax.swing.JTextField();
        jColonia = new javax.swing.JTextField();
        jInstruccion = new javax.swing.JTextField();
        jDescanso = new javax.swing.JTextField();
        jBotonPausa = new javax.swing.JButton();
        jAlmacen = new javax.swing.JTextField();
        jContAlmacen = new javax.swing.JTextField();
        jLlevando = new javax.swing.JTextField();
        jComedor = new javax.swing.JTextField();
        jContComedor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jExterior.setText("Ext");

        jColonia.setText("Colonia");
        jColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColoniaActionPerformed(evt);
            }
        });

        jInstruccion.setText("instruccion");
        jInstruccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInstruccionActionPerformed(evt);
            }
        });

        jDescanso.setText("descanso");

        jBotonPausa.setText("Detener");
        jBotonPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonPausaActionPerformed(evt);
            }
        });

        jAlmacen.setText("almacen");
        jAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlmacenActionPerformed(evt);
            }
        });

        jContAlmacen.setText("ContAlmacen");
        jContAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContAlmacenActionPerformed(evt);
            }
        });

        jLlevando.setText("Llevando");
        jLlevando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLlevandoActionPerformed(evt);
            }
        });

        jComedor.setText("Zona comer");
        jComedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComedorActionPerformed(evt);
            }
        });

        jContComedor.setText("ContComedor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLlevando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonPausa)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jContAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jContComedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jExterior)
                        .addComponent(jColonia, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                        .addComponent(jInstruccion)
                        .addComponent(jDescanso)
                        .addComponent(jAlmacen)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jExterior, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jInstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jContAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jContComedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLlevando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jBotonPausa)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jColoniaActionPerformed

    private void jInstruccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInstruccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInstruccionActionPerformed

    private void jBotonPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonPausaActionPerformed
        if(!botonPulsado) //Si no se ha pulsado
        {                 
            botonPulsado=true;             
            jBotonPausa.setText("Reanudar");  
            c.pausar();
            c.consolaLog("Se ha pausado la ejecucion del programa");
        }
        else //Si ya se había pulsado
        {                           
            botonPulsado=false;           
            jBotonPausa.setText("Detener"); 
            c.reanudar();
            c.consolaLog("Se ha reanudado la ejecucion del programa");
        }
    }//GEN-LAST:event_jBotonPausaActionPerformed

    private void jAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlmacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAlmacenActionPerformed

    private void jContAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContAlmacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jContAlmacenActionPerformed

    private void jLlevandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLlevandoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLlevandoActionPerformed

    private void jComedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAlmacen;
    private javax.swing.JButton jBotonPausa;
    private javax.swing.JTextField jColonia;
    private javax.swing.JTextField jComedor;
    private javax.swing.JTextField jContAlmacen;
    private javax.swing.JTextField jContComedor;
    private javax.swing.JTextField jDescanso;
    private javax.swing.JTextField jExterior;
    private javax.swing.JTextField jInstruccion;
    private javax.swing.JTextField jLlevando;
    // End of variables declaration//GEN-END:variables
}
